export const DEFAULT_COMMAND_FILES = [
  "addText.jsx",
  "canvasImportExport.jsx",
  "imageSearch.jsx",
  "removeNodeFromCurrentGroup.jsx",
  "stitchExport.jsx",
  "clip.jsx",
  "pi-agent-assistant",
  // "poseSearch.jsx",
  // "imageGene.jsx",
  // "multiSearch.jsx",
  // "copySelectedImageToClipboard.jsx",
  // "packageCanvasAssetsZip.jsx",
  // "openSelectedImageInFolder.jsx",
];
